<?php
include('beta_settings.php');
include('memcached.php');
include('session.php');
include('db_info.php');
include('email.php');
include('username.php');
include('encryption.php');
include('mg.php');
require('Mobile_Detect.php');
?>